### ISSUE TITLE
I/O with Eigen

### ISSUE THREAD

**Issue by neuroking** [RTXI/rtxi#102]
Hello,

I am having trouble reading data into and out of Eigen's Matrix class.

For example, if I have the following matrix initialized 
initParameters(void){ 
// Initialize 6x1 matrix
MatrixXd X(6,1);
X << 0, 0, 0, 0, 0, 0;
}

How do I insert inputs and extract values for output?
X(0) = input(0);  // Does not work and RTXI crashes
output(0) = X(0); // Does not work and RTXI crashes

The program compiles just fine, but I get this error:

rtxi: ./Eigen/src/Core/DenseCoeffsBase.h:394: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::DenseCoeffsBase<Derived, 1>::Index) [with Derived = Eigen::Matrix<double, -1, -1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = double; Eigen::DenseCoeffsBase<Derived, 1>::Index = long int]: Assertion `index >= 0 && index < size()' failed.
terminate called without an active exception

Thanks

Vivek

**Comment by anselg** [comment]
It looks like a scope issue. Is MatrixXd X declared as a class member in your header file? 

What happens is when you defined MatrixXd X(6,1) in initParameters(), it creates a local variable that's destroyed once out of scope. The execute() function then calls the class variable X. It wasn't initialized, so you run into bounds errors when trying to access a member of it. 

Try changing:
```
MatrixXd X(6,1);
```
to: 
```
X  = MatrixXd(6,1);
```

and be sure that X is a member of the plugin class.
