### ISSUE TITLE
Error when launching rtxi from terminal

### ISSUE THREAD

**Issue by neuroking** [RTXI/rtxi#104]
Hello,

We get the following error message when we type in rtxi or sudo rtxi into the command terminal:
Xenomai: /dev/rtheap is missing
(chardev, major=10 minor=254)

We have the latest version of rtxi installed. 

What do I need to do to fix this? 

Thank you

Vivek

**Comment by yapatel** [comment]
You're not booted into the RT kernel. You can check which kernel you are booted into by typing "uname -r" at the command line. 

When your computer boots, hold the right shift key to get the grub menu and select the kerne with "Xenomai" in the name. 

Yogi

**Comment by anselg** [comment]
What is the output of 'uname -r' ?

You may not be running a real-time kernel. See FAQ #1:
http://rtxi.org/docs/#faqs

**Comment by anselg** [comment]
It was a simple question, so I'm guessing it's resolved by now. For future reference, please close thread if your issue is fixed.

**Comment by neuroking** [comment]
Gotcha, thanks for the fast answer! I'll make sure to close any future threads after they are completed .

Vivek      

Sent from Yahoo Mail on Android 
 
  On Tue, Jun 14, 2016 at 4:58 PM, anselg<notifications@github.com> wrote:   
It was a simple question, so I'm guessing it's resolved by now. For future reference, please close thread if your issue is fixed.

**Comment by oPiZiL** [comment]
I met the same problem.   
`uname -a`  
``` 
Linux louw-desktop 4.9.51-xenomai-3.0.5-aufs #1 SMP Sat Dec 23 20:47:47 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
```
