### ISSUE TITLE
Accidentally deleted all .so files

### ISSUE THREAD

**Issue by neuroking** [RTXI/rtxi#105]
Hello,

I accidentally deleted all of the .so files. All of the modules are gone. Is there a simple command I can type in the terminal to install the base modules including oscilloscope, control panel, etc...? 

Thank you
Vivek

**Comment by anselg** [comment]
For base modules, reinstall rtxi. Go to the scripts directory of your rtxi
repository and run:

$ ./install_rtxi.sh
