### ISSUE TITLE
Data recorder doesn't save channel names with non-ascii characters. 

### ISSUE THREAD

**Issue by anselg** [RTXI/rtxi#111]
RTXI v2.1 (xenial branch)
HDF v1.8.16 (from the xenial package repos) 

When recording from the connor-stevens neuron, if the data recorder is set to record any channels that have characters like `(` or `^`, it fails to record the channel name. This results in the number of names under Synchronous Data to be less than the number of columns in the Channel Data table. 

Side note - the analysis module will crash when trying to open an hdf file malformed this way.

**Comment by yapatel** [comment]
Resolved in 76a031b5ed6c2094b9febd1cf514e4d2d1774bf3
