### ISSUE TITLE
number of channels

### ISSUE THREAD

**Issue by JohnV7** [RTXI/rtxi#117]
Hi guys,

how many simultaneous channels does rtxi support? What is the upper bound?

Best,
John

**Comment by yapatel** [comment]
Theoretically you can do 32 channels with the National Instruments DAQ, but this limit is really dependent upon how fast you want the real-time period to be.

What are your specific needs? Some of our on-going devs may be suited for your needs. If you'd prefer to discuss off line, you can do so at yogi <at> rtxi <dot> org.
