### ISSUE TITLE
Does anyone use RTXI with Open Ephys acquisition board?

### ISSUE THREAD

**Issue by Inescaetano91** [RTXI/rtxi#118]
Hi! I know that RTXI is extremely used in intracellular recording and stimulation, such as Dynamic Clamp. However, I didn't see works in the extracellular fields (to record local field potentials, stimulate some brain areas, recording spikes). Do you know if this kind of recording/stimulation/processing is possible with RTXI and what kind of acquisition board is advised? Moreover, it is possible to use the acquisition board of open ephys to signal acquisition and use RTXI to process and create stimulation protocols? (I think that in 2016 this was a future goal of the group, and that RTXI is only compatible with NI acquisitions boards.. but i would like to know if there was some improvements in this field). 
Thanks

**Comment by yapatel** [comment]
Hi - the OpenEphys system does not interface with RTXI. The primary reason is that the USB-based communication protocol does not allow for deterministic hard-real time control. 

Right now your primary option is an NI DAQ. We are working on other options and will make notify the community when ready. You can find a list of DAQs [here](http://rtxi.org/docs/manual/#daqs). 

RTXI will digitize any input signal you give it - LFPs, EEG, single units, etc. We've outlined a few examples of this flexibility in the [paper](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005430).
