### ISSUE TITLE
RTXI 2.0 amd64 image installed, but xenomai test failed

### ISSUE THREAD

**Issue by oPiZiL** [RTXI/rtxi#119]
RTXI 2.0 amd64
## Basic Information: 
**RTXI Version:RTXI 2.0 amd64
**Installed from Live CD?:RTXI 2.0 amd64

## Error Description: 

**What happened?**
./test_rt_kernel.sh failed

**What was supposed to happen?**
/dev/rtheap missing

**What steps will trigger the error?**

## Error Message: 

Copy error messages and terminal output between the two braces below. 

```
xenomai : /dev/rtheap missing
```

**Comment by yapatel** [comment]
Please make sure you are booted into the RT kernel. You can check which kernel you are booted into by typing `uname -r`

**Comment by oPiZiL** [comment]
`uname -r`
`3.16.0-77-generic`
So, how could I boot into RT kernel

**Comment by oPiZiL** [comment]
I modified 

> /etc/default/grub
`GRUB_HIDDEN_TIMEOUT=0`-->`GRUB_HIDDEN_TIMEOUT=10`

then I restart the system. The screen goes grey, So I press ESC. I selected xenomai mennuentry, BUT I can't go into graphics desktop.

**Comment by yapatel** [comment]
It sounds like you may be missing the right graphics driver for your card. Are you using a dedicated graphics card or on board graphics?

**Comment by oPiZiL** [comment]
It's an onboard graphic card.

 one more question:

If I upgrade the Ubuntu 14.04 to 16.04, would it work in RT kernel?

**Comment by yapatel** [comment]
Typically the OS and the kernel are not dependent upon each other. That being said, there could be kernel dependencies that cause issues.  

If you have 14.04 working, then there is no significant benefit to jumping to 16.x. Both are LTS versions and function for RTXI.  

Yogi

**Comment by yapatel** [comment]
has this issue been resolved?

**Comment by oPiZiL** [comment]
RT kernel  works after upgrade
