### ISSUE TITLE
Problem installing the RTXI

### ISSUE THREAD

**Issue by URSUroman** [RTXI/rtxi#137]
## Basic Information: 
**RTXI Version:2.2 
**Installed from Live CD?: no, compiled from source

## Error Description: 

**What happened?**
While following the instructions from http://rtxi.org/install/ (custom), every thing went fine till step 6.
After launching the script ./install_rt_kernel.sh, the kernel edition window doesn't allow to disable the Power Management and ACPI options (Processor, the Frequency Scaling and the CPU Idle PM support).

**What was supposed to happen?**
I saw that there was a recent update of several scripts in the rtxi repository. Before that update, I managed to set up RTXI on several machines without much problems. I think the inability to disable some options is due to the recent updates.
I don't know how important is it to disable the frequency scaling for the correct running of rtxi. Could it affect the real-time stability? I stopped the installation at that point.

**Comment by fusge** [comment]
Thanks for submitting this bug. Right now RTXI is on version 2.3 whcih supports installation on newer software (Ubuntu 20.04 LTS, Xenomai 3.1), however some of the steps for compiling the kernel on the website are outdated. Currently we are in the process of testing these differences and updating the website to reflect these changes. 

Initial testing suggests that not disabling these options did not have a noticeable impact on performance, particularly when setting the update frequency in the system control panel. I recommend finishing the installation and seeing if performance is degraded on your setup. If you have any more questions feel free to email me at ivan@rtxi.org and we can discuss further.
