### ISSUE TITLE
Control panel 

### ISSUE THREAD

**Issue by thiagoburghi** [RTXI/rtxi#150]
## Basic Information: 
**RTXI Version:** 
3.0.2
**Installed from Live CD?:** 
No

## Error Description: 
Configurations in the "Analog Channels" section of the control panel widget seem to have a bug.

**What happened?**
The problem seems to depend on whether "Active" has been selected at least once for a channel.
If channel has never been active:
Set configuration (example: scale) to some value (example: 100), choose the order of magnitude (example: milli-), and click "apply". The configuration is reset to the default value.
If channel is active or was active at some previous point:
Set configuration (example: scale) to some value (example: 100), choose the order of magnitude (example: milli-), and click "apply". The configuration value changes to a different value (but not the default one) than the one which was selected.

**What was supposed to happen?**
Clickling "apply" should save the correct "Analog configurations" for the duration of the session. (I am not sure if the behaviour experienced for "inactive" channels was intended).

**What steps will trigger the error?**
The error can be triggered immediately by running a fresh session of RTXI and opening the control panel widget. 

## Error Message: 
The only message displayed by the terminal after clicking "apply" is not an error:
```
[ 2024-02-22 04:43:30 ] (TELEMITRY)	 TYPE --  System Devicelist Updated
[ 2024-02-22 04:43:30 ] (EVENT FIRED)	 TYPE -- SYSTEM : Period value requested
```

**Comment by fusge** [comment]
This seems like a straightforward bug to fix. In the event that you click apply the configuration of the channel should be stored regardless of whether the channel is active or not but the observed behavior ignores changes if the channel is not active.

Thanks for submitting. Will submit an update for rtxi 3.0.3

**Comment by fusge** [comment]
fixed was added to development branch. Next release will have the fix.
