### ISSUE TITLE
Control panel setting issue

### ISSUE THREAD

**Issue by hxywang7** [RTXI/rtxi#153]
## Basic Information: 
**RTXI Version:
3.0.2
**Installed from Live CD?:
No

## Error Description: 

**What happened?**
Analog display issue:
Set configuration (example: scale) for control panel to some value (example: 1), choose the order of magnitude (example: milli-), and click "apply". The scale will change from 1 to 1e-3 with milli. Then if continue to click apply without changing scale, then the scale will become 1e-6

**What was supposed to happen?**
The scale number should keep same 

**What steps will trigger the error?**
Any time change the scale 

## Note:
The bug is located at line 559  in system_control.cpp (dev branch)
`analogGainEdit->setText(QString::number(gain));`

Bug can be fixed by
`analogGainEdit->setText(QString::number(tmp));`

Line 577 should also be changed to
`analogZeroOffsetEdit->setText(QString::number(tmp));`

**Comment by fusge** [comment]
Thanks for submitting. Change applied and merged to dev branch.
