### ISSUE TITLE
Bug with installing 3.0.3 version

### ISSUE THREAD

**Issue by hxywang7** [RTXI/rtxi#155]
## Basic Information: 
**RTXI Version:** 
3.0.3
**Installed from Live CD?:**
no

## Error Description: 

**What happened?**
After running ./scripts/install_rtxi.sh, the analysis module cannot be installed.

**What was supposed to happen?**

**What steps will trigger the error?**

## Error Message: 

Copy error messages and terminal output between the two braces below. 

```
Make Error at /usr/share/cmake-3.22/Modules/FindHDF5.cmake:241 (try_compile):
  Unknown extension ".c" for file

    /tmp/rtxi_modules/analysis-module/build/CMakeFiles/hdf5/cmake_hdf5_test.c

  try_compile() works only for enabled languages.  Currently these are:

    CXX

  See project() command to enable other languages.
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FindHDF5.cmake:596 (_HDF5_test_regular_compiler_C)
  CMakeLists.txt:26 (find_package)


```

## Notes:
Bug is in CMakeList.txt for analysis-module

```
project(
    analysis-module
    VERSION 0.1.0
    DESCRIPTION "View hdf5 data recorded by the Data Recorder plugin"
    HOMEPAGE_URL "https://rtxi.org/"
    LANGUAGES CXX
)
```

Bug is fixed by adding C language
```
LANGUAGES C CXX
```

**Comment by fusge** [comment]
The fix was applied to relevant plugin installation script
