### ISSUE TITLE
Downsample setting issue in control panel

### ISSUE THREAD

**Issue by hxywang7** [RTXI/rtxi#156]
## Basic Information: 
**RTXI Version:** 
3.0.3
**Installed from Live CD?:**
No

## Error Description: 

**What happened?**
Down sample value cannot be changed in control panel

**What was supposed to happen?**

**What steps will trigger the error?**

## Error Message: 

Copy error messages and terminal output between the two braces below. 

```

```

## Notes:
Function **_dev->getAnalogDownsample_** and **_dev->setAnalogDownsample_** in **_nidaq_driver.cpp_** has not been developed. They both return 0.

**Comment by fusge** [comment]
Fix applied to dev branch. Update available in next patch release.
