### ISSUE TITLE
Oscilloscope offset bug

### ISSUE THREAD

**Issue by hxywang7** [RTXI/rtxi#161]
## Basic Information: 
**RTXI Version:** 
3.0.3
**Installed from Live CD?:**
No

## Error Description: 

**What happened?**
The oscilloscope offset value cannot be set. When click on apply button, the offset value will be automatically set to be 0.

**What was supposed to happen?**

**What steps will trigger the error?**

## Error Message: 

Copy error messages and terminal output between the two braces below. 

```

```

**Comment by thiagoburghi** [comment]
New version seems to have corrected this, thanks!
