### ISSUE TITLE
Oscilloscope UI doesn't update properly when plotting input channels for modules

### ISSUE THREAD

**Issue by anselg** [RTXI/rtxi#68]
When plotting the inputs to modules (neuron in this case), the oscilloscope UI will revert back to the 'disabled' appearance when "Apply" is hit to enable a channel, but it will still plot the signal like it's supposed to. 

See the below screenshot. The signal-generator is connected to the neuron module. The signal waveform is in red, and Iapp for the neuron module in blue. Notice that the UI for Iapp has buttons greyed out, as if the Iapp channel is disabled in the oscilloscope. 

![screenshot from 2015-05-26 19 15 28](https://cloud.githubusercontent.com/assets/6200846/7825519/ea19b5c6-03db-11e5-8161-c3307b8e0f20.png)

This behaviour changes when the the Vm output of the neuron module is enabled. Instead of the oscilloscope showing neuon's Iapp being disabled, it is enabled, even if it's not being plotted. See below:
![screenshot from 2015-05-26 19 24 13](https://cloud.githubusercontent.com/assets/6200846/7825605/df41743a-03dc-11e5-9b23-64ccd9bde1e8.png)

It seems the UI is looking at the state of the Output channel of the module to determine the state of the Input channel.

**Comment by yapatel** [comment]
I am unable to reproduce this error; please pull the latest master branch, recompile, and verify that you are using the latest version Help->About RTXI (should show rc3).

**Comment by anselg** [comment]
Fixes to the issue are already on the master branch. Pulling them into the qt5 branch fixed the issue.
