### ISSUE TITLE
Oscilloscope default size is big and it does not resize. 

### ISSUE THREAD

**Issue by anselg** [RTXI/rtxi#71]
All the members of my lab currently using RTXI have complained that in 2.0, the oscilloscope cannot be resized. They also want to be able to hide the buttons on the bottom of the module so that the oscilloscope module doesn't take up as much space on the screen. On smaller monitors (I don't recall their resolutions), it can end up occupying most of the display.  

Also, they haven't mentioned this, but I think it would also be helpful to allow the oscilloscope (and the system modules, too) to be minimized.

**Comment by yapatel** [comment]
Size has been reduced by a small factor and window controls have been restored.
