### ISSUE TITLE
Oscilloscope will not trigger for some signals. 

### ISSUE THREAD

**Issue by anselg** [RTXI/rtxi#74]
There seem to be a few ways to mess with triggering.  (qt5 branch, commit d6336d2bca55b2e188ef53f51cc3a1ed4cc0d6c0)

My setup:  
 - 2 signal generators outputting sine waves at different frequencies. Other settings were left at defaults.  
 - the mimic module offsetting one of the signal generators by 4 (V).  

I plotted all of these signals in the oscilloscope (20 ms/div and each signal at 1 V/div). No offsetting in the oscilloscope itself. 

Error 1: The oscilloscope will not trigger when the threshold is set to 0 V on the signals centered at 0 and when set to 4 V on the mimic signal offset by 4 V. The oscilloscope just looks like its paused. Setting the threshold to 1 mV or 4.001 V, respectively, will enable triggering. 

Error 2: The oscilloscope window will occasionally 'flicker' such that the triggered signal twitches horizontally away from where it is supposed to be. I can get this to happen when signal generator 1 is set to 15 Hz and signal generator 2 at 14 Hz. (This happens at other frequencies, too.) Other parameters were left at defaults.

**Comment by yapatel** [comment]
Sorry for the delay in this. The scope has had some other updates to it recently - and the triggered has been modified. All of this is working as it should on the setups tested here.

Note - triggered with a threshold of 0V is really not triggering. The threshold value (even on a physical oscilloscope) needs to be a non-zero number.
