### ISSUE TITLE
Offset in the input/output in RTXI under Xenomai

### ISSUE THREAD

**Issue by Hananel-Hazan** [RTXI/rtxi#82]
I think that there is an offset in the measurement of the input in the DAQ card, here is my test setup:
rtxi-2.0 latest update run from installation of ubuntu-v7-amd64.iso
DAQ: PCI-6259 National Instruments 
1. Volt Generator connect to the Input of the DAQ card.
2. Volt Meter with two inputs. Input 1 of the Volt Meter connected to Volt Generator and Input 2 of the Volt Meter to the Output of the DAQ card.
3. At RTXI connect DAQ input to DAQ output 
4. Open Oscilloscope in RTXI.

Set the Volt Generator to 500mV
Result:
On the Volt Meter appear:
Input 1 = 500mV  (from the volt generator)
input 2 = 475mV (from the output of the DAQ)
Oscilloscope in RTXI show 475mV from the DAQ input.

Set the Volt Generator to 1V
Result:
On the Volt Meter appear:
Input 1 = 1V  (from the volt generator)
input 2 = 950mV (from the output of the DAQ)
Oscilloscope in RTXI show 950mV from the DAQ input.

Set the Volt Generator to 2V
Result:
On the Volt Meter appear:
Input 1 = 2V  (from the volt generator)
input 2 = 1.9V (from the output of the DAQ)
Oscilloscope in RTXI show 1.9V from the DAQ input.

Change the OS to Windows 8.1 with National Instrument drivers and check the same setup, the results were accurate.

Change the OS to RTXI 1.4 ubuntu 9.10 x86 from ubuntu-9.10-desktop-amd64-rtxi-4.iso and check the same setup, the results were accurate (output were equal to the input).

**Comment by yapatel** [comment]
I'm not able to reproduce this on 3 machines.

But let's see if we can tease this apart.

Create a workspace with the following:

- Test output calibration
1. Use the signal generator module to create a sine wave of amplitude=0.5, frequency=10, and the other settings as is.
2. Set the system frequency to 10kHz
3. Enable one of the DAQ output channels
4. Connect the signal generator output to the enabled DAQ output channel from step 3
5. Visualize the output on a scope or multimeter - what is the amplitude of the sine wave? 
6. Simultaneously, save the DAQ output via the data recorder. Record about 60s.

- Test input calibration
1. Set a function generator to output a sine wave of amplitude 1V, frequency 10Hz. 
2. Plug that into an available DAQ input
3. Set the system frequency to 10kHz
4. Enable the DAQ input (whichever one you connected to in step 2)
5. Setup the data recorder to record that DAQ input
6. Record 60 seconds

Please email the HDF5 files you acquire to yogi at rtxi dot org
