### ISSUE TITLE
Seems to be a limit on number of open channels at higher sampling frequencies

### ISSUE THREAD

**Issue by charless3** [RTXI/rtxi#85]
Changed sampling frequency to 20 kHz. Adding input channels 0 and 1 worked fine. RTXI crashed upon adding input channel 2. This happened with no modules open and nothing running.

**Comment by yapatel** [comment]
This is not a bug. This is a limitation of a high-speed hard RT system that is designed to pipe data around a pipeline in a synchronous fashion.

To use large number of channels at high sampling rates, asynchronous sampling should be used. This is under development and expected to be completed in 1-2 months.
