### ISSUE TITLE
Calling MATLAB routines using engine API through rtxi

### ISSUE THREAD

**Issue by neuroking** [RTXI/rtxi#93]
Hello,

I am interested in using math routines provided by MATLAB either through the real-time thread or asynchronously. I was wondering if anybody has tried to call matlab routines through the matlab engine API (link below).  

http://www.mathworks.com/help/matlab/matlab_external/introducing-matlab-engine.html

Thanks

Vivek

**Comment by yapatel** [comment]
Hi Vivek -

I did some basic testing, and although it's easy to use and functional, I don't recommend using it unless you can guarantee that all your processing will be on the non-RT thread. Any calls to the MATLAB engine through execute (or the functions execute calls) will lead to a dropout from RT mode for an unknown amount of time (until MATLAB finishes it's processing/etc).

If you do use this, I'd be interested in seeing the runtime performance of your system.

Yogi
