### ISSUE TITLE
Model current performs appropriately in Matlab but does not work when run as C++ file in RTXI

### ISSUE THREAD

**Issue by joeyrans** [RTXI/rtxi#94]
Hi,
I've been having some trouble with an RTXI model for dynamic clamp and was wondering if you could offer some help. When the model is run in rtxi with square waves from the signal generator and mimic modules, the current looks as expected. When it is run in clampex with a biological cell, after the first protocol sweep the current becomes inverted and incorrect. If the same protocol sweeps are run through the same equations in the model offline (using matlab)  it looks as expected. So, in matlab the model current performs as is expected however when run in RTXI the model current looks strange and, for some reason, inverts to an incorrect polarity after the first sweep of the protocol. Do you have any suggestions for what could be going wrong and causing the differences when the model is applied in a realtime manner, using RTXI, as opposed to being run offline in Matlab?  I am happy to provide the C++, header and make files used in RTXI as well as the Matlab script if that will help.  I can also send you the ABF recording when the model is turned on and behaving inappropriately if it will help.  

I will very much appreciate any help you can provide me.

Joey Ransdell

**Comment by yapatel** [comment]
Hi Joey -

Can you email those resources to me at yogi at rtxi.org?

Also, which version of RTXI are you running  and what is the system frequency you are using?

Yogi
